"use client"
import './globals.css'
import { Inter } from 'next/font/google';
import NewNavbar from "./components/NewNavbar";
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script></head>
      <body className={inter.className}>
        <NewNavbar />
        {children}
      </body>
    </html>
  )
}